title: "pyUnpackQA"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "GitHub Repo":
    - "//github.com/sdtaylor/pyUnpackQA"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

